# Generated by Django 3.1 on 2022-02-08 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doc_manager_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='document',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='folder',
        ),
        migrations.AddField(
            model_name='topic',
            name='name',
            field=models.CharField(default='abc', max_length=1024),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TopicAssociation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='doc_manager_app.document')),
                ('folder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='doc_manager_app.folder')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doc_manager_app.topic')),
            ],
        ),
    ]
